In [1]:
import pandas as pd
from scipy.stats import chi2_contingency

In [2]:
df = pd.read_csv("../Files/Amazon.csv",low_memory=False)
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [3]:
cancelled_pending_orders = df[df["Status"].isin(['Cancelled','Pending'])]

contingency_table = pd.crosstab(cancelled_pending_orders["Status"],cancelled_pending_orders['Fulfilment'])

In [4]:
print(contingency_table)

Fulfilment  Amazon  Merchant
Status
Cancelled    11471      6861
Pending        415       243

In [5]:
chi2 , p , dof, ex = chi2_contingency(contingency_table)
print("Chi-Squared statistic : " , chi2)
print(f"P-Value : {p}")
print(f"Degree of freedom : {dof}")
print(f"Expected Values : {ex}")

Chi-Squared statistic :  0.04729799287402296
P-Value : 0.8278334990054204
Degree of freedom : 1
Expected Values : [[11474.15229068  6857.84770932]
 [  411.84770932   246.15229068]]

In [6]:
if p < 0.05:
    print(f"Reject null hypothesis")
else:
    print(f"Fail to reject null hypothesis")

Fail to reject null hypothesis

### Exercise : (a) Was geder and survival independent in titanic? (b) Were passenger class and survival related in titanic?

In [7]:
df = pd.read_csv("../Files/titanic.csv")
df

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [8]:
# a 
contingency_table = pd.crosstab(df["survived"],df['gender'])

In [9]:
chi2 , p , dof, ex = chi2_contingency(contingency_table)
print("Chi-Squared statistic : " , chi2)
print(f"P-Value : {p}")
print(f"Degree of freedom : {dof}")
print(f"Expected Values : {ex}")

Chi-Squared statistic :  260.71702016732104
P-Value : 1.1973570627755645e-58
Degree of freedom : 1
Expected Values : [[193.47474747 355.52525253]
 [120.52525253 221.47474747]]

In [11]:
if p < 0.05:
    print(f"Reject null hypothesis")
else:
    print(f"Fail to reject null hypothesis")

Reject null hypothesis

In [12]:
# b

In [13]:
contingency_table = pd.crosstab(df["pclass"],df['survived'])

In [14]:
chi2 , p , dof, ex = chi2_contingency(contingency_table)
print("Chi-Squared statistic : " , chi2)
print(f"P-Value : {p}")
print(f"Degree of freedom : {dof}")
print(f"Expected Values : {ex}")

Chi-Squared statistic :  102.88898875696056
P-Value : 4.549251711298793e-23
Degree of freedom : 2
Expected Values : [[133.09090909  82.90909091]
 [113.37373737  70.62626263]
 [302.53535354 188.46464646]]

In [15]:
if p < 0.05:
    print(f"Reject null hypothesis")
else:
    print(f"Fail to reject null hypothesis")

Reject null hypothesis

### Exercise : Does education level decide if a person will get a loan?

In [16]:
df = pd.read_csv("../Files/loan.csv")
df

     age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0     41   3      17       12     176      9.3  11.359392  5.008608      1.0
1     27   1      10        6      31     17.3   1.362202  4.000798      0.0
2     40   1      15       14      55      5.5   0.856075  2.168925      0.0
3     41   1      15       14     120      2.9   2.658720  0.821280      0.0
4     24   2       2        0      28     17.3   1.787436  3.056564      1.0
..   ...  ..     ...      ...     ...      ...        ...       ...      ...
845   34   1      12       15      32      2.7   0.239328  0.624672      NaN
846   32   2      12       11     116      5.7   4.026708  2.585292      NaN
847   48   1      13       11      38     10.8   0.722304  3.381696      NaN
848   35   2       1       11      24      7.8   0.417456  1.454544      NaN
849   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[850 rows x 9 columns]

In [29]:

df["default"] = df["default"].dropna()
contingency_table = pd.crosstab(df["ed"],df['default'])

In [30]:
chi2 , p , dof, ex = chi2_contingency(contingency_table)
print("Chi-Squared statistic : " , chi2)
print(f"P-Value : {p}")
print(f"Degree of freedom : {dof}")
print(f"Expected Values : {ex}")

Chi-Squared statistic :  11.492341703403657
P-Value : 0.02155395852574417
Degree of freedom : 4
Expected Values : [[274.74857143  97.25142857]
 [146.23714286  51.76285714]
 [ 64.25571429  22.74428571]
 [ 28.06571429   9.93428571]
 [  3.69285714   1.30714286]]

In [31]:
if p < 0.05:
    print(f"Reject null hypothesis")
else:
    print(f"Fail to reject null hypothesis")

Reject null hypothesis